### ISSUE TITLE
估计是我的配置太奇葩了，，，，囧，试用失败

### ISSUE THREAD

**Issue by tossp** [dengsgo/fileboy#4]
```
D:\src\golang\src\tsl>fileboy -v                                                
                                                                                
 _______ _____ _       _______ ______   _____  _     _                          
(_______|_____) |     (_______|____  \ / ___ \| |   | |                         
 _____     _  | |      _____   ____)  ) |   | | |___| |                         
|  ___)   | | | |     |  ___) |  __  (| |   | |\_____/                          
| |      _| |_| |_____| |_____| |__)  ) |___| |  ___                            
|_|     (_____)_______)_______)______/ \_____/  (___)   V1.6                    
         This world is so lonely without you.                                   
                                                                                
Dengsgo [dengsgo@gmail.com] Open Source with MIT License                        
                                                                                
 Version   fileboy: v1.6    filegirl: v1                                        
Released   2019.1.19                                                            
 Licence   MIT                                                                  
  Author   dengsgo [dengsgo@gmail.com]                                          
 Website   https://github.com/dengsgo/fileboy                                   
    Blog   https://www.yoytang.com                                              
                                                                                
```

第一次测试

```yml
command:
    exec:
        - go fmt ./..
        - go build -v -ldflags "-s -w -linkmode internal -extldflags \"-static\""
        - tsl
```

```
[FileBoy]: 05:13:11 EVENT WRITE : D:\src\golang\src\tsl\modules\_blank\model\index.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x652a93]

goroutine 243 [running]:
os.(*ProcessState).exited(...)
        C:/go/src/os/exec_posix.go:70
os.(*ProcessState).Exited(...)
        C:/go/src/os/exec.go:146
main.(*TaskMan).preRun(0xc000065350, 0xc00033a630)
        C:/goWork/src/fileboy/taskman.go:48 +0x43
main.(*TaskMan).Put.func1(0xc000065350, 0xc00033a630)
        C:/goWork/src/fileboy/taskman.go:43 +0x7f
created by main.(*TaskMan).Put
        C:/goWork/src/fileboy/taskman.go:38 +0xa3

```

换一下配置

```yml
command:
    exec:
        - go fmt {{file}}
        - go build -v -ldflags "-s -w -linkmode internal -extldflags \"-static\""
        - tsl
```

```
[FileBoy]: 05:14:52 fileboy is ready.
[FileBoy]: 05:14:55 EVENT RENAME : main.go
[FileBoy]: 05:14:57 Warn: notifier call url ignore.
[FileBoy]: 05:14:57 EXEC [go fmt main.go]
main.go
[FileBoy]: 05:14:58 EVENT WRITE : main.go
[FileBoy]: 05:14:58 EVENT WRITE : main.go
[FileBoy]: 05:14:58 EXEC [go build -v -ldflags "-s -w -linkmode internal -extldflags \"-static\""]
invalid value "\"-s" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
[FileBoy]: 05:14:58 Warn: cmd wait err  exit status 2
[FileBoy]: 05:14:58 end
[FileBoy]: 05:15:00 Warn: notifier call url ignore.
[FileBoy]: 05:15:00 EXEC [go fmt main.go]
[FileBoy]: 05:15:01 EXEC [go build -v -ldflags "-s -w -linkmode internal -extldflags \"-static\""]
invalid value "\"-s" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
[FileBoy]: 05:15:01 Warn: cmd wait err  exit status 2
[FileBoy]: 05:15:01 end
```

**Comment by dengsgo** [comment]
```yaml  
command:
    exec:
        - go build -v -ldflags "-s -w -linkmode internal -extldflags \"-static\""
```

这条命令不支持。  
另外我重现了一下你的问题，导致 fileboy 进程挂掉的原因是一个bug，需要修复发一个新版
