### ISSUE TITLE
执行的命令会被强制中断

### ISSUE THREAD

**Issue by yeyu12** [dengsgo/fileboy#8]
希望执行的命令不要强制中断，并且希望加入初始化执行命令

**Comment by dengsgo** [comment]
由于 `fileboy`  无法预估命令执行的时长，为防止执行中的命令一直阻塞，导致后续的命令任务响应滞后，现在采用的策略是有新任务进来就直接中断之前的任务（而不管它是否还在执行）。  
你说的这种情况，可能是你的命令执行的时长比较久，如果不想命令被中断，可以把 `filegirl.yaml` 配置的中 `command  delayMillSecond` 参数值设的大一些，大于你的命令执行时长。    
```yaml
command:
    # 把这个值设置的大一些，大于你的命令执行时长
    delayMillSecond: 60000
```  
  
这样的话后续的任务会排队，直到超过这个时长之后才会执行。
